---
title: "Introduction/Background"
author: "Matt Clark & Alex Killion"
date: "4/27/2020"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Intro/ Background
Wildfires have been increasing in frequency and severity across the U.S. primarily in the West. While the direct impacts of worsening wildfires have been extensively measured and reported both in the academic literature and the popular media, the indirect, or secondary effects are not as well understood. One of these secondary effects is the production of widespread wildfire smoke. Smoke, which is a mixture of gases and particulate matter, poses a considerable risk to human health. Because of these health risks, people who live in areas affected by wildfire smoke are frequently cautioned against recreating outdoors following fire events. It is anecdotally understood that individuals abide by these warnings and limit time spent outdoors when large amounts of ambient smoke are present. We do not however, currently understand the exact relationship between wildfire smoke and population level recreation behavior. For example, we do not know if the effects are linear or if there is a threshold after which the majority of individuals will decide to stay indoors, but not before. Furthermore, the theory of 'shifting baselines' suggests that individuals may tolerate normally intolerable degrees of environmental disturbance when the disturbance is framed against an already highly disturbed location or point in time. In other words, human response to envionmetal disturbance is relative. 

To get an estimate of how populations behave as a result of wildfire smoke, we will use the visitation records collected by the National Park Service. We will couple these data with spatial data on the Dust Surface Mass Concentration at or below 2.5, the primary health concern generated by wildfire smoke. These spatial data were obtained from NASA's Modern-Era Retrospective analysis for Research and Applications version 2 (MERRA-2) satellite. 

Increasing wildfire severity has further garnered attention for the financial burden it poses to the federal government. The United States spends approximately $1 billion every year to fight wildfires. This however, only approximates the direct costs of wildfire relief. Given that outdoor recreation is significantly affected by wildfire smoke, a secondary goal of this project will be to generate an order of magnitude estimate on National Park Service revenue lost due to increased wildfire smoke. 


## 4/27 Meeting Notes

* Top 10 most visited parks?
* Remove relativelysmokeless parks? cutoff?
* Keep only parks where smoke season overlaps with high visitation season
* Selection bias? 
  + Keep parks in areas where wildfires are expected to increase?
  + Stratify on the independent variable, not the depemdent
  + Design analysis to ensure that the experimental treatment behaves consistently
  
  
* How is increasing smoke affecting parks in smoke vulnerable places? How is this expected to continue into the future? 

Parks are the crown jewl of the america public lands system. They are already financially burdened. Think of pictures of overwhelmed trashcans, bears, condors eating trash, etc. One of the biggest things that affect them financially negatively and they have no control over is smoke. They don't control surrounding forest service land etc. Climate change might affect the financial strain on the park service, here's how? 

* Path Forward
1. subset highsmoke/high season
2. varying effects of smoke and distance from airport, varying intercept for each park, varying slope on AR term
3. Alex will look for future fire vulnerability 
4. Alex will look into distance from airport





