---
title: "Untitled"
author: "Alex Killion"
date: "7/20/2020"
output: html_document
---

Import NPS Boundaries 
```{r}
#Data From - https://public-nps.opendata.arcgis.com/datasets/national-park-service-park-unit-boundaries

nps<-readOGR("/Volumes/GoogleDrive/My Drive/Local/Projects/Smoke/Smoke-Signal/NPS_poly/NPS_poly.shp")

#select only polygons designated as National Parks
nps<-nps[nps@data$UNIT_TYPE=="National Park",]

#remove National Parks outside our Regions
nps<-nps[nps@data$REGION=="PW"|nps@data$REGION=="IM",]
nps<-nps[nps@data$UNIT_CODE!="NPSA",] #Samoa
nps<-nps[nps@data$STATE!="HI",]

#reformat to use park codes later
nps_df<-as.data.frame(nps)
nps_df<-as.matrix(nps_df$UNIT_CODE)

park_codes<-as.data.frame(nps_df)
names(park_codes)<-"park"

```



```{r}

poly<-sf::st_as_sfc(nps) #converts to new type of poly


list_all<- list.files("/Users/killion/Downloads/Random_Month",full.names = TRUE)

empty_list<-list()

for (i in 1:length (list_all)) {
    for (j in 1:length (list_all[[i]])){
 bcphilic<-mean(brick(list_all[[i]][[j]], varname="BCPHILIC", level=72)) #one day - first bracket is month, 2nd is day, within a day is 8 layers by hour - the "level" dimension refers to veritcal layers where 72=surface and 1=top of atmosphere
bcphobic<-mean(brick(list_all[[i]][[j]], varname="BCPHOBIC", level=72))
ocphilic<-mean(brick(list_all[[i]][[j]], varname="OCPHILIC", level=72))
ocphobic<-mean(brick(list_all[[i]][[j]], varname="OCPHOBIC", level=72))

all<-bcphilic+bcphobic+ocphilic+ocphobic

empty_list[[j]]<-exact_extract(all, poly, 'mean') #intersects boundary

    }
  
out<-as.data.frame(empty_list)
out_mean_random<-as.data.frame(rowMeans(out, na.rm=TRUE)) #take mean of the assign list above

   
#write csv
  n<-substr(list_all[[i]][[j]],94,100) # !!!!!!!! you will have to change 94 and 100 based on the length of your filepaths - this selects just the year and month i.e. 20041008
  colnames(out_mean)[1] <- n #give values column name based on month
   name<-paste0("/Users/killion/output_means/",n) #create empty folder to save to
    newname<-paste0(name, ".csv")
write.csv(out_mean, newname, row.names = FALSE) #save as csv

  }

#loads those .csv and makes into single df
list_dates = list.files(path="/Users/killion/output_means/", pattern="*.csv", full.names=TRUE) #same folder you saved above output

final_means<-list_dates %>%
  map(read_csv) %>%
  reduce(cbind)

#append park code
final_means<-data.frame(park=park_codes, final_means)

#save
write.csv(final_means, "/Users/killion/final_means2.csv", row.names = FALSE)

```

