---
title: "Rationale and Hypotheses"
author: "Matt Clark & Alex Killion"
date: "11/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Testing - What is the best way to replicate a Word comment bubble when editing specific text in document?


## Project Rationale
Wildfires have been increasing in frequency and severity across the U.S. primarily in the West. While the direct impacts of worsening wildfires have been extensively measured and reported both in the academic literature and the popular media, the indirect, or secondary effects are not as well understood. One of these secondary effects is the production of widespread wildfire smoke. Smoke, which is a mixture of gases and particulate matter, poses a considerable risk to human health. Because of these health risks, people who live in areas affected by smoke post-wildfire are frequently cautioned against recreating outdoors following fire events. It is anecdotally understood that individuals abide by these warnings and limit time spent outdoors when large amounts of ambient smoke are present. We do not understand however, if individuals decide to reduce time spent outdoors as a result of top-down warnings like the Air Quality Index, or if they make these decisions through individual observation of atmospheric smoke, which we can measure with Dust Surface Mass Concentration. Furthermore, the exact relationship between wildfire smoke and people's decision making is unclear. We do not, for example, know if the effects are linear or if there is a threshold after which the majority of individuals will decide to stay indoors, but not before.

To get an estimate of how populations behave as a result of wildfire smoke, we will use the visitation records collected by the National Park Service. We will couple these data with spatial data on the Dust Surface Mass Concentration at or below 2.5, the primary health concern generated by wildfire smoke. These spatial data were obtained from NASA's Modern-Era Retrospective analysis for Research and Applications version 2 (MERRA-2) satellite. We will also attempt to disentangle these actual atmospheric smoke estimates from the Air Quality Indexes produced by the National Weather Service. This will allow us to estimate to what degree populations base their recreation decisions on top-down or bottom-up influences.

## Hypotheses

### H0
We observe no difference in national park visitation as a result of actual wildfire smoke recorded by the MERRA-2 satellite or Air Quality Indexes reported by the National Weather Service.

**Inference:** Individuals do not change their outdoor recreation behavior as a result of wildfire smoke.

### H1
We observe significantly lower reported park visitation during months with high levels of wildfire smoke recorded by the MERRA-2 satellite, but not during months with dangerous Air Quality Indexes reported by the National Weather Service.

**Inference:** Individuals significantly change their outdoor recreation behavior as a result of wildfire smoke based on personal observations and bottom-up decision making.

### H2
We observe significantly lower reported park visitation during months with dangerous Air Quality Indexes reported by the National Weather Service but not during months with high levels of wildfire smoke recorded by the MERRA-2 satellite.

**Inference:** Individuals significantly change their outdoor recreation behavior as a result of wildfire smoke based on public warnings and top-down influences.
